# Generated by Django 3.2.6 on 2021-08-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do post'),
        ),
    ]
