# Generated by Django 3.2.6 on 2021-08-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_imagem_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link da imagem do post'),
        ),
    ]
