# Generated by Django 3.2.6 on 2021-08-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=150, verbose_name='Nome')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto_contato', models.CharField(max_length=150, verbose_name='Assunto')),
                ('conteudo_contato', models.TextField(verbose_name='Mensagem')),
                ('data_contato', models.DateTimeField(auto_now_add=True)),
                ('resolvido_contato', models.BooleanField(default=False, verbose_name='Resolvido')),
            ],
        ),
    ]
