# Generated by Django 3.2.6 on 2021-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210812_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='conteudo_comentario',
            field=models.TextField(verbose_name='Comentário'),
        ),
    ]
