# Generated by Django 3.2.6 on 2021-08-17 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comentarios', '0003_alter_comentario_conteudo_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor_post_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor do post'),
        ),
    ]
